import { useLocale } from "@/locales/LocaleProvider";

const zh = {
  kicker: "HISTORY / REGISTERED STUDY", title: "投资方式与历史", intro: "用已登记的快照、行为证据和可比较范围回看投资过程。它不评分、不诊断，也不预测。",
  history: "个人历史与 Twin", compare: "比较分析", synthetic: "确定性 Synthetic 独立研究", asOf: "数据截至", currentSlice: "当前历史切面", currentSliceDetail: "来自 TwinSnapshot 的可追溯状态投影。", open: "持有中的投资经历", closed: "已结束的投资经历", state: "组合状态", evidence: "已完成证据 / 证据不足",
  registered: "已登记历史", hhi: "组合集中度（HHI）", turnover: "交易活跃度", hhiDetail: "快照描述持仓分布；不判断集中是否更好。", turnoverDetail: "只描述登记窗口内的实际交易。", historyMethod: "方法与来源", myPast: "相对自己的过去", myPastDetail: "百分位只描述当前观测在已登记个人历史中的位置。", personalPercentile: "个人历史百分位", historyInsufficient: "历史不足",
  behavior: "当前行为观察", behaviorDetail: "处置效应和亏损状态加仓有已登记的当前证据，但尚未形成历史序列。", disposition: "处置效应", loss: "亏损状态加仓", currentOnly: "当前观察；未形成历史序列", method: "方法", sample: "样本", investmentExperiences: "快照引用的投资经历", investmentDetail: "同一证券清仓后重新建仓仍是不同 Episode。", ongoing: "进行中", ended: "已结束",
  selfPast: "与过去的自己比较", selfPastDetail: "仅展示已注册的集中度与换手率快照。", sameStock: "同股路径比较", sameStockDetail: "已有一个与当前研究无关的隔离合成双 Episode 示例。真实比较须先经 Episode 范围的授权分享。", openExample: "打开隔离的合成双路径示例", consent: "此工作区不创建邀请，也不扩大访问范围。",
  cohort: "可比群体预览", cohortDetail: "这是明确标识的确定性合成群体，不是对真实投资者的排名。", current: "当前值", median: "合成群体中位数", sourceLimits: "来源与限制", unavailable: "待接入", realCohort: "真实群体比较", realCohortDetail: "需要带群体定义、观察期、来源和最低样本量的运行时合同。", noHistory: "处置 / 亏损加仓的历史", noHistoryDetail: "没有注册的历史序列或个人历史比较结果，前端不会补算。",
  studyRequired: "投资历史必须与所属账户一一对应", realMissing: "当前真实账户尚未提供历史行为、Twin 或群体比较的运行时接口；页面不会替换成示例数据。", mismatch: "当前演示账户与已登记 History/Twin 数据集不一致；为避免误归属，内容没有加载。", openStudy: "打开已登记的 History study", studyAvailable: "可打开独立的已登记 History study", studyDetail: "它是独立的确定性 Synthetic 数据集，不是当前演示账户。", noStudy: "该账户仍可从“我的投资”查看已有权威持仓与 Episode。",
  complete: "已完成", partial: "部分完成", insufficient_evidence: "证据不足", experimental: "试验性", available: "可用", unavailableState: "不可用",
  classicTwin: "查看原版 Twin 详情",
  ask: "在问投镜中选择自己的 Episode", cohortDefinition: "群体定义", metricN: "指标样本 N", percentile: "百分位",
} as const;
const en: Record<keyof typeof zh, string> = {
  kicker: "HISTORY / REGISTERED STUDY", title: "Investment style & history", intro: "Review registered snapshots, behavioral evidence, and comparison scope. This is not a score, diagnosis, or forecast.",
  history: "History & Twin", compare: "Comparisons", synthetic: "Deterministic synthetic independent study", asOf: "Data as of", currentSlice: "Current historical slice", currentSliceDetail: "A traceable state projection from TwinSnapshot.", open: "Open investment episodes", closed: "Closed investment episodes", state: "Portfolio state", evidence: "Complete evidence / insufficient evidence",
  registered: "Registered history", hhi: "Portfolio concentration (HHI)", turnover: "Trading activity", hhiDetail: "The snapshot describes holdings distribution; it does not judge concentration.", turnoverDetail: "Only recorded trades in the registered window are described.", historyMethod: "Method & source", myPast: "Against my past", myPastDetail: "A percentile only locates the current observation in registered personal history.", personalPercentile: "Personal-history percentile", historyInsufficient: "Insufficient history",
  behavior: "Current behavior observations", behaviorDetail: "Disposition and loss-state additions have registered current evidence, but no historical series yet.", disposition: "Disposition", loss: "Loss-state additions", currentOnly: "Current observation; no historical series", method: "Method", sample: "Sample", investmentExperiences: "Episodes referenced by this snapshot", investmentDetail: "A new position after a full exit remains a different Episode.", ongoing: "In progress", ended: "Closed",
  selfPast: "Against my past", selfPastDetail: "Only registered concentration and turnover snapshots appear here.", sameStock: "Same-stock paths", sameStockDetail: "An isolated synthetic two-Episode example exists independently of this study. Real comparison first requires Episode-scoped sharing consent.", openExample: "Open isolated synthetic example", consent: "This workspace creates no invite and expands no access.",
  cohort: "Cohort preview", cohortDetail: "This is an explicitly labelled deterministic synthetic cohort, not a ranking of real investors.", current: "Current", median: "Synthetic cohort median", sourceLimits: "Source & limitations", unavailable: "Not connected", realCohort: "Real cohort comparison", realCohortDetail: "A runtime contract with definition, observation period, provenance, and minimum N is required.", noHistory: "Disposition / loss-addition history", noHistoryDetail: "There is no registered time series or personal-history result, so the frontend does not calculate one.",
  studyRequired: "Investment history must match its account", realMissing: "The current real account has no runtime API for behavioral history, Twin, or cohort comparison. This page never substitutes demo data.", mismatch: "This demo account does not match the registered History/Twin dataset, so content is withheld to avoid false attribution.", openStudy: "Open registered History study", studyAvailable: "A registered independent History study is available", studyDetail: "It is an independent deterministic Synthetic dataset, not the current demo account.", noStudy: "This account can still use My Investments for authoritative positions and Episodes.",
  complete: "Complete", partial: "Partial", insufficient_evidence: "Evidence insufficient", experimental: "Experimental", available: "Available", unavailableState: "Unavailable",
  classicTwin: "Open classic Twin details",
  ask: "Choose your own Episode in Ask Toujing", cohortDefinition: "Cohort definition", metricN: "Metric N", percentile: "Percentile",
};
export function useHistoryCopy() { return useLocale().locale === "zh-CN" ? zh : en; }
