import { useLocale } from "@/locales/LocaleProvider";

const zh = {
  investments: "我的投资", strategy: "策略历史模拟", myStrategies: "我的策略", analysis: "分析与对比", prepare: "决策准备", data: "数据与账户", settings: "设置",
  analysisHome: "开始分析", review: "投资复盘", history: "我的历史", comparison: "对比分析", ask: "问投镜", journal: "决策记录",
  pause: "暂停动态背景", play: "播放动态背景", menu: "打开导航", close: "关闭导航",
  intro: "把经历，变成下一次的判断依据。", introDetail: "从一轮投资开始，回看操作、对照历史，再追问差异背后的依据。",
  reviewTitle: "这轮投资，是怎样走过来的？", reviewDetail: "沿着价格与操作回看完整过程，把值得注意的事实放回发生时的上下文。",
  historyTitle: "与过去的自己对照", historyDetail: "查看已有历史快照与行为证据。只有同一账户的可用历史才参与展示。",
  compareTitle: "相似标的，不同的投资过程", compareDetail: "从同股案例、自己的历史和已注册的示例分布中，选择适合的问题。",
  askTitle: "带着一个问题，继续深入", askDetail: "从整个账户出发，聊聊整体表现、持仓和变化，也可以深入某一轮投资。",
  open: "进入工作区", recorded: "已记录事实", availability: "按账户与证据可用性展示", consent: "需运行环境与授权",
  compareIntro: "换一个参照，看清自己的投资。", compareDescription: "与过去的自己、同股投资者和专业人员对照，理解结果与操作的差别。",
  selfTitle: "自我前后对比", selfDetail: "沿着真实日期，看看自己的持仓结构和交易方式发生了什么变化。",
  pairTitle: "同一只股票对比", pairDetail: "同一只股票，不同的买入、加减仓与退出路径，会呈现怎样的投资经历？",
  professionalTitle: "与专业人员的全盘对比", professionalDetail: "从整个账户出发，对照收益与回撤、持仓配置和操作方式，不只看某一只股票。",
  professionalStatus: "完整研究组合 · Synthetic",
  sharedTitle: "查看获授权的分享", sharedDetail: "从选定投资的分析工作区进入既有分享流程；本机存在另一账户不等于获得许可。",
  synthetic: "年度投资示例 · Synthetic", gated: "需匹配账户 / 可用历史", shared: "限定投资 · 明确授权",
  boundary: "没有证据的地方，不用猜测填满。", boundaryDetail: "历史不足、尚未接入或未获授权的内容会保留边界提示。示例数据始终与真实账户分开。",
  cardAction: "回看这轮投资", emptyTitle: "你的投资，值得被完整理解。", emptyDetail: "把成交记录留在本机。从第一轮投资开始，看清发生了什么，哪些操作值得再看一次。",
  dark: "深海玻璃", light: "晨光玻璃",
};
const en: Record<keyof typeof zh, string> = {
  investments: "My investments", strategy: "Strategy simulation", myStrategies: "My strategies", analysis: "Analysis & comparison", prepare: "Decision preparation", data: "Data & accounts", settings: "Settings",
  analysisHome: "Start here", review: "Investment review", history: "My history", comparison: "Compare", ask: "Ask Toujing", journal: "Decision notes",
  pause: "Pause background motion", play: "Play background motion", menu: "Open navigation", close: "Close navigation",
  intro: "Turn experience into perspective.", introDetail: "Start with an investment. Revisit its decisions, compare the history, then ask what the evidence supports.",
  reviewTitle: "How did this investment unfold?", reviewDetail: "Revisit prices and executions in context, with the recorded facts that deserve a closer look.",
  historyTitle: "Meet your past self", historyDetail: "Explore available snapshots and behavioral evidence. History must belong to the selected account.",
  compareTitle: "Similar assets. Different journeys.", compareDetail: "Choose a same-stock example, your own history, or a registered sample distribution.",
  askTitle: "Follow a question further", askDetail: "Start with your whole account: performance, holdings and changes. Explore an individual investment when needed.",
  open: "Open workspace", recorded: "Recorded facts", availability: "Account and evidence dependent", consent: "Runtime & consent required",
  compareIntro: "A different reference. A clearer perspective.", compareDescription: "Compare with your past self, same-stock investors and professionals to understand differences in outcomes and decisions.",
  selfTitle: "Self: before and after", selfDetail: "Follow real dates to see how your allocation and trading activity have changed.",
  pairTitle: "Same-stock comparison", pairDetail: "Compare entry, additions, reductions and exits in the same stock to understand different investment journeys.",
  professionalTitle: "Full-portfolio professional comparison", professionalDetail: "Compare the entire account: returns and drawdowns, allocation and trading approach—not just one stock.",
  professionalStatus: "Complete research portfolios · Synthetic",
  sharedTitle: "Explore an authorized share", sharedDetail: "Use the existing sharing flow in a selected investment's analysis workspace. Local account access is not consent.",
  synthetic: "Investment-year showcase · Synthetic", gated: "Matching account / history required", shared: "Episode-bound · Explicit consent",
  boundary: "Missing evidence stays visible.", boundaryDetail: "Unavailable history, disconnected capabilities and missing consent are clearly identified. Examples stay separate from real accounts.",
  cardAction: "Review this investment", emptyTitle: "Your investments, in perspective.", emptyDetail: "Keep your recorded executions local. Start with one investment: understand what happened, then find the decisions worth revisiting.",
  dark: "Deep glass", light: "Daylight glass",
};
export function useLiquidCopy() { return useLocale().locale === "zh-CN" ? zh : en; }
