import type { Locale } from "@/locales/LocaleProvider";

const zh = {
  currentHistory: "当前在我的历史中",
  historyIntro: "查看现在的持仓集中度与交易活跃度，分别落在这组账户记录的什么位置。这是对已记录状态的描述，不是评分或预测。",
  currentAsOf: "当前记录截至 {date}",
  threeMonths: "近 3 个月",
  twelveMonths: "近 12 个月",
  allHistory: "全部已记录历史",
  concentration: "持仓集中度",
  concentrationDetail: "描述非现金持仓之间的集中程度；数值较高表示更集中，并不代表更好。",
  turnover: "交易活跃度",
  turnoverDetail: "描述已记录日期的日度交易强度；它不等同于投资能力。",
  current: "当前",
  p25: "P25",
  median: "历史中位位置",
  p75: "P75",
  personalPosition: "我在已记录历史中的位置",
  percentile: "第 {value} 百分位",
  recordedRange: "已记录区间",
  aboveRange: "当前值高于这段已记录历史的大多数观察值。",
  withinRange: "当前值处在这段已记录历史的中间范围内。",
  belowRange: "当前值低于这段已记录历史的大多数观察值。",
  insufficient: "这段已记录历史还不足以定位当前值。",
  historyChart: "实际记录的历史走势",
  basis: "比较的是同一账户在真实记录日期上的状态；缺少的日期不会补入。",
  sameObservations: "目前可用记录较短，因此三个回看范围包含相同的有效观察值。",
  periodTitle: "两个时期的比较",
  periodDetail: "这部分会在后端生成两个完整时期的统一口径结果后单独显示，不与当前历史位置混为一谈。",
  unavailable: "当前账户还没有可比较的个人历史",
  unavailableDetail: "这个页面只使用同一账户的已接入历史。真实账户没有相应运行时数据时，不会替换成示例。",
  mismatchDetail: "当前选择的账户与已登记历史不匹配，因此内容没有加载。",
  example: "打开年度投资示例",
  demoContext: "年度投资示例 · Synthetic · 非真实账户",
} as const;

type SelfComparisonCopy = Record<keyof typeof zh, string>;

const en: SelfComparisonCopy = {
  currentHistory: "Where I am in my recorded history",
  historyIntro: "See where today’s concentration and trading activity sit within this account’s recorded history. This describes recorded states; it is not a score or forecast.",
  currentAsOf: "Current record as of {date}",
  threeMonths: "Past 3 months",
  twelveMonths: "Past 12 months",
  allHistory: "All recorded history",
  concentration: "Holdings concentration",
  concentrationDetail: "Describes concentration among non-cash holdings. A higher value means more concentration, not better investing.",
  turnover: "Trading activity",
  turnoverDetail: "Describes daily trading intensity on recorded dates. It is not a measure of investment ability.",
  current: "Current",
  p25: "P25",
  median: "Recorded middle",
  p75: "P75",
  personalPosition: "My position in recorded history",
  percentile: "{value}th percentile",
  recordedRange: "Recorded range",
  aboveRange: "The current value is above most observations in this recorded history.",
  withinRange: "The current value sits in the middle range of this recorded history.",
  belowRange: "The current value is below most observations in this recorded history.",
  insufficient: "There is not yet enough recorded history to place the current value.",
  historyChart: "Recorded history over time",
  basis: "This compares states from the same account on their actual recorded dates; missing dates are not filled.",
  sameObservations: "The available record is currently short, so all three lookback ranges contain the same valid observations.",
  periodTitle: "Compare two periods",
  periodDetail: "This will appear separately once the backend provides like-for-like results for two complete periods. It is not the same as the current position in history.",
  unavailable: "Comparable personal history is not connected for this account",
  unavailableDetail: "This page only uses history connected to the same account. When a real account has no runtime data, it never substitutes an example.",
  mismatchDetail: "The selected account does not match the registered history, so nothing is loaded.",
  example: "Open investment-year showcase",
  demoContext: "Investment-year showcase · Synthetic · not a real account",
};

export const selfComparisonCopy: Record<Locale, SelfComparisonCopy> = { "zh-CN": zh, "en-US": en };
